-- ============================================================
-- 已废弃（2026-09-12 业务确认）：现行口径为教务核定的本学期值直接计入 G11。
-- 下列学年值说明仅为历史记录，不再用于当前代码或数据准备；不要执行示例 ×2 转换。
-- 新结构见 01_biz_schema.sql / 22_semester_position_workload.sql。
-- 20_service_rate_semantics.sql —— 管理服务岗位标准统一为「学年值」
--
-- 依据《办法》（2026-09-10 统一口径）：
--   第十六条 各岗位补贴标准均为「学时/学年」（院长类 360、系主任/教研室
--     主任 180、专业负责人 100、俱乐部经理 120、实验员 90、班主任 180/班），
--     注文「均以学期为单位进行核算，每学期最高累计不超过180」→ 学年值 ÷2
--   第十七条 教学督导 15 学时/学期 —— 本身即学期值，引擎不折半
--
-- 代码侧：ManagementItemGeneratorImpl 恢复 ÷2（督导除外）。
-- 表列注释本就写「该岗位标准学时/学年」，本次消除「注释写学年、代码按
-- 学期用」的 A-1 矛盾。
--
-- ⚠ 数据迁移须知：
--   本机库 biz_role_assignment 为空表，无迁移必要。
--   若某环境的该表存有 A3 修复之后录入的数据（当时按「学期值」口径），
--   需先把非督导岗位的 allowance_rate ×2 再上线本版本：
--
--   -- 迁移前人工核对：
--   SELECT id, role_type, allowance_rate FROM biz_role_assignment
--    WHERE status = 1 AND role_type <> '督导';
--   -- 确认无误后执行（督导已是学期值，不动）：
--   UPDATE biz_role_assignment
--      SET allowance_rate = allowance_rate * 2,
--          update_by = 'system', update_time = NOW(),
--          remark = CONCAT(IFNULL(remark,''), '；2026-09-10 学年值迁移×2（第十六条）')
--    WHERE status = 1 AND role_type <> '督导';
--
-- 幂等：本文件在空库/新库执行无副作用（仅注释与说明，无 DDL/DML）。
-- ============================================================

-- 无需结构性变更：allowance_rate 列类型 DECIMAL(10,2) 足以承载学年值。
